import {globelAction} from '../action/globel'
import {globelMutation} from '../mutation/globel'

const globel = {
    state:{
        pop:{
            showPop:false,
            text:"123"
        },
        cart:[{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品零食",
            price:'16',
            count:'2',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:1
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品12",
            price:'66',
            count:'5',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:2
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'24',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:3
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'24',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:4
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'24',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:5
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'24',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:6
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'24',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:7
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'24',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:8
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'24',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:9
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'24',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:10
          },{
            title:"可比克有所薯（口味随机）105g*3罐休闲膨化食品13",
            price:'26',
            count:'4',
            picture:'/static/img/banner3.jpg',
            select:false,
            show:false,
            id:11
          }]

    },
    actions:globelAction,
    mutations:globelMutation
}


export default globel;